export interface MenuItem {
  id: string
  name: string
  description: string
  price: number
  image: string
  calories: number
  category: string
  popular?: boolean
  rating: number
  prepTime: string
}

export const categories = [
  { id: "all", label: "All", icon: "grid" },
  { id: "burgers", label: "Burgers", icon: "beef" },
  { id: "pizzas", label: "Pizzas", icon: "pizza" },
  { id: "indian", label: "Indian", icon: "soup" },
  { id: "italian", label: "Italian", icon: "utensils" },
  { id: "beverages", label: "Beverages", icon: "cup-soda" },
  { id: "crushers", label: "Crushers", icon: "glass-water" },
] as const

export const menuItems: MenuItem[] = [
  {
    id: "smash-burger",
    name: "Smash Burger",
    description: "Double-stacked smash patties with melted American cheese, caramelized onions, pickles, and our signature Burger Babai sauce on a toasted brioche bun.",
    price: 249,
    image: "/images/smash-burger.jpg",
    calories: 680,
    category: "burgers",
    popular: true,
    rating: 4.8,
    prepTime: "15-20 min",
  },
  {
    id: "classic-burger",
    name: "Classic Cheeseburger",
    description: "Juicy beef patty with cheddar cheese, fresh lettuce, tomato, and mayo on a sesame bun.",
    price: 199,
    image: "/images/smash-burger.jpg",
    calories: 550,
    category: "burgers",
    rating: 4.6,
    prepTime: "12-18 min",
  },
  {
    id: "margherita-pizza",
    name: "Margherita Pizza",
    description: "Hand-tossed dough topped with San Marzano tomato sauce, fresh mozzarella di bufala, basil leaves, and extra virgin olive oil.",
    price: 349,
    image: "/images/margherita-pizza.jpg",
    calories: 820,
    category: "pizzas",
    popular: true,
    rating: 4.9,
    prepTime: "20-25 min",
  },
  {
    id: "pepperoni-pizza",
    name: "Pepperoni Pizza",
    description: "Crispy thin crust loaded with mozzarella cheese and spicy pepperoni slices, finished with oregano.",
    price: 399,
    image: "/images/margherita-pizza.jpg",
    calories: 900,
    category: "pizzas",
    rating: 4.7,
    prepTime: "20-25 min",
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    description: "Tender chicken pieces simmered in a rich, creamy tomato-based curry with aromatic spices. Served with garlic naan and basmati rice.",
    price: 329,
    image: "/images/butter-chicken.jpg",
    calories: 720,
    category: "indian",
    popular: true,
    rating: 4.9,
    prepTime: "25-30 min",
  },
  {
    id: "paneer-tikka",
    name: "Paneer Tikka Masala",
    description: "Grilled paneer cubes in a spiced tomato and cream gravy, garnished with fresh cilantro. Served with naan.",
    price: 279,
    image: "/images/butter-chicken.jpg",
    calories: 620,
    category: "indian",
    rating: 4.7,
    prepTime: "25-30 min",
  },
  {
    id: "penne-arrabbiata",
    name: "Penne Arrabbiata",
    description: "Al dente penne pasta tossed in a fiery tomato sauce with garlic, red chili flakes, and fresh basil. Topped with shaved Parmigiano-Reggiano.",
    price: 299,
    image: "/images/penne-arrabbiata.jpg",
    calories: 580,
    category: "italian",
    popular: true,
    rating: 4.7,
    prepTime: "18-22 min",
  },
  {
    id: "carbonara",
    name: "Spaghetti Carbonara",
    description: "Classic Roman pasta with pancetta, egg yolk, pecorino cheese, and black pepper in a silky sauce.",
    price: 349,
    image: "/images/penne-arrabbiata.jpg",
    calories: 650,
    category: "italian",
    rating: 4.8,
    prepTime: "18-22 min",
  },
  {
    id: "mango-lassi",
    name: "Mango Lassi",
    description: "A refreshing blend of ripe Alphonso mangoes and creamy yogurt, sweetened with a touch of honey and topped with saffron strands and crushed pistachios.",
    price: 129,
    image: "/images/mango-lassi.jpg",
    calories: 220,
    category: "beverages",
    popular: true,
    rating: 4.8,
    prepTime: "5 min",
  },
  {
    id: "iced-chai",
    name: "Iced Masala Chai",
    description: "Traditional spiced tea with cardamom, cinnamon, and ginger, served over ice with a splash of milk.",
    price: 99,
    image: "/images/mango-lassi.jpg",
    calories: 150,
    category: "beverages",
    rating: 4.6,
    prepTime: "5 min",
  },
  {
    id: "mint-mojito-crusher",
    name: "Mint Mojito Crusher",
    description: "A revitalizing crushed ice drink with fresh mint, lime juice, soda water, and a hint of sugar. The perfect refresher on a warm day.",
    price: 149,
    image: "/images/mint-mojito-crusher.jpg",
    calories: 160,
    category: "crushers",
    popular: true,
    rating: 4.7,
    prepTime: "5 min",
  },
  {
    id: "strawberry-crusher",
    name: "Strawberry Crusher",
    description: "Blended strawberries with crushed ice, lemon zest, and sparkling water for a fruity frozen delight.",
    price: 149,
    image: "/images/mint-mojito-crusher.jpg",
    calories: 180,
    category: "crushers",
    rating: 4.6,
    prepTime: "5 min",
  },
]
